# ============================================================
# Trello Loop Configuration
# Generated by trello-mcp-enhanced setup.
# All project-specific values for the QA automation loop.
# Update this file to reconfigure — then restart the MCP server.
# ============================================================

# --- Trello Lists ---
# To find list IDs: call trello_get_lists in Claude Code.
trello:
  watchList:
    name: {{WATCH_LIST_NAME}}
    id: "{{WATCH_LIST_ID}}"
  inboxList:
    name: {{INBOX_LIST_NAME}}
    id: "{{INBOX_LIST_ID}}"
  inProgressList:
    name: {{IN_PROGRESS_LIST_NAME}}
    id: "{{IN_PROGRESS_LIST_ID}}"
  readyForQAList:
    name: {{READY_FOR_QA_LIST_NAME}}
    id: "{{READY_FOR_QA_LIST_ID}}"

# --- Git Repos ---
# Each repo the loop can commit to.
# name:         Short name passed to shipit-auto.sh ("client", "api", etc.)
# ghSlug:       GitHub owner/repo for gh -R commands
# deployBranch: Branch for direct pushes and PR base
# pathPrefix:   Subdirectory prefix for file detection (empty for root repo)
{{REPOS_YAML}}

# --- Scripts & Loop ---
shipitScript: {{SHIPIT_SCRIPT}}      # Commit/push script in project root
branchPrefix: "qa/"                   # Feature branch prefix for PRs
pollIntervalMinutes: {{POLL_INTERVAL}}

# --- Classification Rules ---
# These control how cards are sorted into simple / complex / out-of-scope.
classification:

  # Cards touching more files than this are automatically out of scope.
  maxFilesPerCard: {{MAX_FILES}}

  # What counts as "complex but doable" — Claude handles these via PR.
  # Add or remove items to tune what the loop will attempt.
  complexDoable:
    - Simple CSS changes (colors, spacing, font sizes, visibility)
    - Centralizing constants (extracting repeated values)
    - Adding or swapping CSS classes
    - Swapping component props
    - Updating static data (arrays, objects with display data)
    - Fixing TypeScript types
    - Renaming variables within a single file
    - Removing clearly dead code

  # What is always out of scope — card goes back to Inbox with a comment.
  outOfScope:

    # If the card references a file matching any of these path fragments,
    # it's out of scope. Keeps the loop away from sensitive areas.
    filePatterns:
{{FILE_PATTERNS_YAML}}

    # If the card description contains any of these keywords (case-insensitive),
    # it's out of scope. Catches intent even without a file path.
    keywords:
{{KEYWORDS_YAML}}

    # Human-readable descriptions of out-of-scope categories.
    # Used in Trello comments when rejecting cards.
    descriptions:
      - UI structure changes (adding/removing components from DOM)
      - API route changes
      - Database or migration changes
      - Auth or security changes
      - Adding external package imports
      - Changing game mechanics
